### ISSUE TITLE
[Bug]  npm install  does not works

### ISSUE THREAD

**Issue by guaranta** [creativetimofficial/ct-argon-dashboard-chakra-pro#1] opened 2022-03-21 00:00 UTC
### Version
1.0
### Reproduction link
https://jsfiddle.net/
### Operating System
Mac OS Catalina
### Device
macbook air
### Browser & Version
chrome Version 99.0.4844.74
### Steps to reproduce
1. Download Argon Dashboard Chakra Pro from creative-tim club account
2. npm install

### What is expected?
It works
### What is actually happening?
didn't work

---
### Solution
react-custom-scrollbars its not compatible with react17 ? Can you fix that ??

When I try npm install --legacy-peer-deps  , but did not works as well. 
### Additional comments

terminal outputs:

npm install                    
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: argon-dashboard-chakra-pro@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-custom-scrollbars@4.2.1
npm ERR! node_modules/react-custom-scrollbars
npm ERR!   react-custom-scrollbars@"^4.2.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /my_user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /my_user/.npm/_logs/2022-03-20T23_27_35_855Z-debug-0.log

**Comment by simmmpleweb** [comment] 2022-03-22 19:18
Hello, @guaranta ! Thanks for using our products ! The error is caused by a conflict between peer dependencies. For now, npm --force install should work, and soon we'll change the plugin that is causing the trouble. As fast as we solve the problem, I'll come back with a comment and close the issue. Regards, Vlad.

**Comment by guaranta** [comment] 2022-03-22 22:23
Hello, @simmmpleweb !

After run  "npm --force install" and,
a lot of 

> "npm WARN ERESOLVE overriding peer dependency"

some 

> "npm WARN deprecated"

and a huge list of things like 

> npm ERR! gyp ERR! build error  and 'remove_cv_t' references

I suspected that it is  over a known one that node-sass doesn't support Node 16^ versions issue
 
So I run

> CXXFLAGS="--std=c++14"  npm --force install

And finally works. But I believe we shouldn't let the product be deprecated; I would like to see a solution to the real dependency problem.

**Comment by simmmpleweb** [comment] 2022-03-27 10:41
Hello! We did the update to 1.0.1 so now the product works as it should! Regards, Vlad.

**Closed as completed by simmmpleweb** 2022-03-27 10:41 UTC
